User: softwarepublico
UpdateRate: 600
GitDomain: http://softwarepublico.gov.br
GitSpecPath: gitlab/softwarepublico/softwarepublico/raw/<branch>/src/pkg-rpm/<package>/<package>.spec
Repositories:
  - v5
  - v6
Branches:
  - stable-5.0
  - master
